### ISSUE TITLE
Check optifine compat

### ISSUE THREAD

**Issue by Dani-BoBani** [fredo1029/Create-Agriculture#6]
Iris compat with flywheel seemed to not be working
Optifine broekn early on, not added back yet

**Comment by Dani-BoBani** [comment]
Optifine will not be the efficiency mod going forward.
Check Sodium, Indium compat with forgified fabric API.

**Comment by cjhammons** [comment]
Find mod to make harvesting tall trees easier. Either:

- Mining out the base of a tree will cause the rest of it to collapse
- Trees get vein-mined

**Comment by Dani-BoBani** [comment]
Embeddium and shaders working properly

**Comment by Dani-BoBani** [comment]
need zoom mod replacement still

**Comment by Dani-BoBani** [comment]
Zoom mods unlikely to work well with LODs. Closing for now.
